### ISSUE TITLE
400 Client Error: Bad Request for url: https://api.tavily.com/search

### ISSUE THREAD

**Issue by robertcedwards** [rotemweiss57/gpt-newspaper#6]
Just cloned and started the creation process, get that error and it hangs.
MacOS: 14.2.1 (23C71)
Python3.9

requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.tavily.com/search
127.0.0.1 - - [25/Jan/2024 11:03:57] "POST /generate_newspaper HTTP/1.1" 500 -

**Comment by robertcedwards** [comment]
Interesting, just Web3 was a 4-char. Let me make sure I properly exported the API keys too, but I think it already made an auth'd call.

**Comment by rotemweiss57** [comment]
perfect. lmk know it works with greater than 4 char topics and I'll update you once fixed.

**Comment by robertcedwards** [comment]
I tried it with just a single topic that had more chars and it worked. Thanks for the help and persistence!

**Comment by robertcedwards** [comment]
Also, running into some rate limits, not sure if there are some error handling issues here, don't think it will try again.
```
File "/Users/robertedwards/Documents/Projects/gpt-newspaper/gpt-newspaper/lib/python3.9/site-packages/openai/_base_client.py", line 959, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-4do9SrRAEt8fzaKFeoFMaM1A on tokens per min (TPM): Limit 10000, Used 9979, Requested 2920. Please try again in 17.394s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
```

**Comment by shaojun** [comment]
I've seen this error as well.
100% happen when input 2 topics (both length>4):
![image](https://github.com/assafelovic/gpt-newspaper/assets/3241829/f0aec902-16d8-4180-9b07-bd23aff6f580)

 and it's good for single topic.

**Comment by badcom** [comment]
I got the same error. I had 3 words in the search. 2 with 6 letters and 1 with 4. None of them had any special characters.
Removing the word with 4 letters resolved it.

**Comment by flyspirit99** [comment]
I got a similar error. After double checked api keys and restarted my computer, everything is fine.

**Comment by Bubbalubagus** [comment]
I still get this error all of the time:
400 Client Error: Bad Request for url: [https://api.tavily.com/search.](https://api.tavily.com/search.) Failed fetching searches error.

Windows, triple checked api key, it seems to be consuming credits, but it also seems to be falling back to using bs4 (beautiful soup) often.
